version: "3.8"
services:

    backend:
        image: docker.io/springcommunity/spring-petclinic-rest:latest
        ports:
        - target: 9966
          published: 9966
          protocol: tcp

    frontend:
        build: ./spring-petclinic-angular/
        image: ddiazsouto/frontend
        ports:
        - target: 8080
          published: 8083
          protocol: tcp